### ISSUE TITLE
Error when using a bot token

### ISSUE THREAD

**Issue by DragonPigGQ** [Mattlau04/discord-message-mirror-cloner#1]
Hi, the following issues occur when i try to run your code, any idea on why this happened? I am using a valid bot token.

```
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

discord.errors.LoginFailure: Improper token has been passed.
```

**Comment by Mattlau04** [comment]
Sorry, the code is made for user tokens
To use a bot token you need to edit the last line of the script
simply replace `client.run(token, bot=False)` by `client.run(token, bot=True)`
